name: Deployment Pipeline

on:
  push:
    branches:
      - dev

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      #- name: Run tests
       # run: ./gradlew test -i

      #- name: Execute Gradle build
       # run: ./gradlew build

      #- uses: gradle/gradle-build-action@v2
       # with:
        #  arguments: check

      - name: Execute Gradle dependencies
        run: ./gradlew dependencies

      #- name: Deploy Heroku App
        #if: success() && github.ref == 'refs/heads/main'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build



      #- name: Install dependencies
       # run: npm install
      #- name: Build
       # run: npm run build
      #- name: Test
       # run: npm test