name: Deployment Pipeline

on:
  push:
    branches:
      - dev

jobs:
  fecha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #- name: Run tests
       # run: ./gradlew test -i


      - name: Install dependencies
        run: npm install --no-audit --no-found --no-optional
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

      - name: Deploy Heroku App
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          #justlogin: true
          #branch: "dev"

      #- name: Deploy Heroku App
       # if: success() && github.ref == 'refs/heads/main'
        #uses: akhileshns/heroku-deploy@v3.12.12
